### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by tiwarivikash** [Kong/lua-resty-events#20]
It would be nice to have some documentation about the design and rationale behind the library. It would help if we can see some guidance on when to use this vs lua-resty-worker-events. Thank you.

**Comment by chronolaw** [comment]
We will post a technology blog about it on konghq.com, maybe in one or two weeks.

**Comment by chronolaw** [comment]
Here is it. https://konghq.com/blog/nginx-openresty-event-handling-strategy-for-cpu-efficiency

**Comment by tiwarivikash** [comment]
> Here is it. https://konghq.com/blog/nginx-openresty-event-handling-strategy-for-cpu-efficiency

Thank you.
