### ISSUE TITLE
How to install by luarocks?

### ISSUE THREAD

**Issue by snpcp** [Kong/lua-resty-events#22]
Hello, 

Thanks your source. Could you tell me how to install this source to my project? use luarocks or other ways?

**Comment by chronolaw** [comment]
No, It don't support luarocks, because it depends on special C code of Nginx.

It should be compiled as an Nginx module with `--add-module`, then run `make install` to copy lua files.

**Comment by snpcp** [comment]
Thanks for your replay, It works.
