### ISSUE TITLE
Can't use callback of compat?

### ISSUE THREAD

**Issue by snpcp** [Kong/lua-resty-events#23]
I want to get worker-pid, but get 'wid' in callback-handle.

Log:
`worker-events: handling event; source=l.r.g.c:GLOBAL_CACHE, event=NEW, wid=13`
Version:
`lua-resty-events master`

**Comment by chronolaw** [comment]
Yes, it is a small difference between `lua-resty-events` and `lua-resty-worker-events`.

Now `wid` means Nginx worker id, not process pid, but you can add pid in param `data`.

**Comment by snpcp** [comment]
Why add callback code for compat. How can I use it?

**Comment by chronolaw** [comment]
I think you can refer to the example code in readme or test cases in the '/t' directory.

**Comment by snpcp** [comment]
How can prevent `source worker process` from receiving a broadcast, this event is unnecessary.

I use `pid == ngx.worker.pid() ` to avoid this event, However, I can't found the `current worker wid` when use `wid`.

**Comment by chronolaw** [comment]
No, you can't. The principle of this library is that all Nginx workers will receive the event, including the sender self.

You can use `ngx.worker.id()` to get the current worker id, please refer to lua-nginx-module document.

**Comment by snpcp** [comment]
Thanks, I will try to adapt `resty-worker-events` with `resty-events` about worker id.
