### ISSUE TITLE
There may be a risk of transient data loss during initial startup

### ISSUE THREAD

**Issue by perfgao** [Kong/lua-resty-events#42]
If the Connect Borker has not succeeded, Publish may result in data loss。

**Comment by chronolaw** [comment]
Sure, perhaps it could be inevitable.

**Comment by bungle** [comment]
@perfgao if you can try this branch:
https://github.com/Kong/lua-resty-events/pull/58

It should fix it.

**Comment by bungle** [comment]
With release `0.3.0`, I consider this fixed. @perfgao, if further issues happen, let us know!
