### ISSUE TITLE
The event worker failed when reloading OpenResty.

### ISSUE THREAD

**Issue by shadow3x3x3** [Kong/lua-resty-events#43]
Hi. 

Whenever I restart OpenResty, this error keeps showing up.

```log
worker.lua:266: communicate(): event worker failed: failed to receive the header bytes: closed, context: ngx.timer
```

And relevant code is as follows:

```lua
local WE_OPTS = {
    unique_timeout = 10,
    broker_id = 0,
    listening = "unix:/tmp/events.sock",
    max_queue_len = 1024 * 50,
    max_payload_len = 65535,
}

local ev = require("resty.events.compat")
local ok, err = ev.configure(WE_OPTS)
```

Although everything works good right now, I still want to understand what's causing this error. Thanks.

**Comment by chronolaw** [comment]
This is because lua-resty-events is using Nginx's unix socket listening. When OpenResty restarting, the socket is closed, so cosocket will get this error.

**Comment by chronolaw** [comment]
Here is a blog post describing the mechanism. https://konghq.com/blog/nginx-openresty-event-handling-strategy-for-cpu-efficiency

**Comment by shadow3x3x3** [comment]
Thanks for your replay.
